theme = "blowfish"
baseURL = "https://dzongsarinstitute.org.in/"

defaultContentLanguage = "bo"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true
summaryLength = 0
buildDrafts = false
buildFuture = true
enableEmoji = true

[pagination]
  pagerSize = 50

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[related]
  threshold = 0
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10
